# SwiftLint configuration for ClaudeNotifier

included:
  - Sources

excluded:
  - "**/*.generated.swift"

disabled_rules:
  - trailing_whitespace

opt_in_rules:
  - empty_count
  - closure_spacing
  - sorted_imports

line_length:
  warning: 120
  error: 200
  ignores_comments: true
  ignores_urls: true
  ignores_function_declarations: true
  ignores_interpolated_strings: true

function_body_length:
  warning: 60
  error: 100

identifier_name:
  min_length:
    warning: 2
    error: 1
  excluded:
    - i
    - id
    - ok
    - x
    - y
